### ISSUE TITLE
crash: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by codezjx** [codezjx/AndLinker#13]
Client app crash when server has been killed.
```
2022-04-18 09:43:40.293 6309-6309/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxx.xxx, PID: 6309
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:540)
        at com.codezjx.andlinker.j$a$a.r1(ITransfer.java:5)
        at com.codezjx.andlinker.a.q(AndLinker.java:4)
        at com.codezjx.andlinker.a.g(AndLinker.java:1)
        at com.codezjx.andlinker.a$b.onServiceDisconnected(AndLinker.java:2)
        at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1973)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1988)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by codezjx** [comment]
Fix in version 0.8.1
