### ISSUE TITLE
 java.lang.NullPointerException: Expected to unbox a 'boolean' primitive type but was returned null

### ISSUE THREAD

**Issue by codezjx** [codezjx/AndLinker#14]
If the server is disconnected, then your client execute the remote method, there will be a crash.
Note: Only appears in scenarios where the return value is the primitive type.
```
2022-04-18 11:25:25.126 18583-18583/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xxxx.your.app, PID: 18583
    java.lang.NullPointerException: Expected to unbox a 'boolean' primitive type but was returned null
        at $Proxy1.foo(Unknown Source)
        at com.xxx.your.app.method(Test.java:101)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by codezjx** [comment]
Fix in version 0.9.0, this crash due to a type conversion mechanism of dynamic proxy.
For more infomation, visit: https://stackoverflow.com/questions/52083338/expected-to-unbox-a-string-primitive-type-but-was-returned-null
