### ISSUE TITLE
Callback 不带参数的方法回调会失败

### ISSUE THREAD

**Issue by JoeSteven** [codezjx/AndLinker#7]
定义了一个回调接口
@RemoteInterface
public interface IFaceRecognizeCallBack {
    void onTrack(@In Rect faceRect);
    void onTrackNoFaces();
    void onRecognize(int state);
    void recognizeSuccess(String faceImagePath, String wholeImagePath);
    void recognizeFail(int reasonType, boolean isLiveness);
}
其他回调都正常，但是回调 onTrackNoFaces() 方法会抛异常，写了其他sample代码发现没有参数的方法都会异常
2019-07-11 11:14:16.173 1750-1783/com.terminus.TSLOpenService W/System.err: java.lang.NullPointerException: Attempt to get length of null array
2019-07-11 11:14:16.173 1750-1783/com.terminus.TSLOpenService W/System.err:     at com.codezjx.andlinker.Invoker.createCallbackRequest(Invoker.java:173)
2019-07-11 11:14:16.173 1750-1783/com.terminus.TSLOpenService W/System.err:     at com.codezjx.andlinker.Invoker.access$100(Invoker.java:18)
2019-07-11 11:14:16.173 1750-1783/com.terminus.TSLOpenService W/System.err:     at com.codezjx.andlinker.Invoker$1.invoke(Invoker.java:154)
2019-07-11 11:14:16.173 1750-1783/com.terminus.TSLOpenService W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
2019-07-11 11:14:16.173 1750-1783/com.terminus.TSLOpenService W/System.err:     at $Proxy4.onTrackNoFaces(Unknown Source)
2019-07-11 11:14:16.173 1750-1783/com.terminus.TSLOpenService W/System.err:     at com.terminus.tslopensdk.ipc.face.recognize.FaceRecognizeImpl.setFaceRecognizeOption(FaceRecognizeImpl.java:19)
2019-07-11 11:14:16.173 1750-1783/com.terminus.TSLOpenService W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-07-11 11:14:16.173 1750-1783/com.terminus.TSLOpenService W/System.err:     at com.codezjx.andlinker.MethodExecutor.execute(MethodExecutor.java:36)
2019-07-11 11:14:16.173 1750-1783/com.terminus.TSLOpenService W/System.err:     at com.codezjx.andlinker.Invoker.invoke(Invoker.java:134)
2019-07-11 11:14:16.173 1750-1783/com.terminus.TSLOpenService W/System.err:     at com.codezjx.andlinker.LinkerBinderImpl.execute(LinkerBinderImpl.java:38)
2019-07-11 11:14:16.173 1750-1783/com.terminus.TSLOpenService W/System.err:     at com.codezjx.andlinker.ITransfer$Stub.onTransact(ITransfer.java:52)
2019-07-11 11:14:16.173 1750-1783/com.terminus.TSLOpenService W/System.err:     at android.os.Binder.execTransact(Binder.java:752)

**Comment by codezjx** [comment]
@JoeSteven 非常感谢反馈此问题！已修复~  明天我抽空更新下版本~  Thanks~

**Comment by codezjx** [comment]
已更新v0.7.2版本~
